/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VerifyEmailImport } from './routes/verify-email'
import { Route as SignupImport } from './routes/signup'
import { Route as SigninImport } from './routes/signin'
import { Route as ServiceUnavailableImport } from './routes/service-unavailable'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as HomeImport } from './routes/home'
import { Route as ForgotPasswordImport } from './routes/forgot-password'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthUsersImport } from './routes/_auth/users'
import { Route as AuthSettingsImport } from './routes/_auth/settings'
import { Route as AuthNoaccessImport } from './routes/_auth/noaccess'
import { Route as AuthFunImport } from './routes/_auth/fun'
import { Route as AuthUsersIndexImport } from './routes/_auth/users/index'
import { Route as AuthProjectsIndexImport } from './routes/_auth/projects/index'
import { Route as AuthProjectsProjectIdIndexImport } from './routes/_auth/projects/$projectId/index'
import { Route as AuthUsersUserIdSettingsImport } from './routes/_auth/users/$userId/settings'
import { Route as AuthProjectsProjectIdAnalysesAnalysisIdIndexImport } from './routes/_auth/projects/$projectId/analyses/$analysisId/index'
import { Route as AuthProjectsProjectIdAnalysesAnalysisIdSuperuserImport } from './routes/_auth/projects/$projectId/analyses/$analysisId/superuser'

// Create/Update Routes

const VerifyEmailRoute = VerifyEmailImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRoute,
} as any)

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const SigninRoute = SigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const ServiceUnavailableRoute = ServiceUnavailableImport.update({
  id: '/service-unavailable',
  path: '/service-unavailable',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const ForgotPasswordRoute = ForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthUsersRoute = AuthUsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSettingsRoute = AuthSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)

const AuthNoaccessRoute = AuthNoaccessImport.update({
  id: '/noaccess',
  path: '/noaccess',
  getParentRoute: () => AuthRoute,
} as any)

const AuthFunRoute = AuthFunImport.update({
  id: '/fun',
  path: '/fun',
  getParentRoute: () => AuthRoute,
} as any)

const AuthUsersIndexRoute = AuthUsersIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthUsersRoute,
} as any)

const AuthProjectsIndexRoute = AuthProjectsIndexImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthProjectsProjectIdIndexRoute = AuthProjectsProjectIdIndexImport.update(
  {
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AuthRoute,
  } as any,
)

const AuthUsersUserIdSettingsRoute = AuthUsersUserIdSettingsImport.update({
  id: '/$userId/settings',
  path: '/$userId/settings',
  getParentRoute: () => AuthUsersRoute,
} as any)

const AuthProjectsProjectIdAnalysesAnalysisIdIndexRoute =
  AuthProjectsProjectIdAnalysesAnalysisIdIndexImport.update({
    id: '/projects/$projectId/analyses/$analysisId/',
    path: '/projects/$projectId/analyses/$analysisId/',
    getParentRoute: () => AuthRoute,
  } as any)

const AuthProjectsProjectIdAnalysesAnalysisIdSuperuserRoute =
  AuthProjectsProjectIdAnalysesAnalysisIdSuperuserImport.update({
    id: '/projects/$projectId/analyses/$analysisId/superuser',
    path: '/projects/$projectId/analyses/$analysisId/superuser',
    getParentRoute: () => AuthRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/service-unavailable': {
      id: '/service-unavailable'
      path: '/service-unavailable'
      fullPath: '/service-unavailable'
      preLoaderRoute: typeof ServiceUnavailableImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailImport
      parentRoute: typeof rootRoute
    }
    '/_auth/fun': {
      id: '/_auth/fun'
      path: '/fun'
      fullPath: '/fun'
      preLoaderRoute: typeof AuthFunImport
      parentRoute: typeof AuthImport
    }
    '/_auth/noaccess': {
      id: '/_auth/noaccess'
      path: '/noaccess'
      fullPath: '/noaccess'
      preLoaderRoute: typeof AuthNoaccessImport
      parentRoute: typeof AuthImport
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsImport
      parentRoute: typeof AuthImport
    }
    '/_auth/users': {
      id: '/_auth/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersImport
      parentRoute: typeof AuthImport
    }
    '/_auth/projects/': {
      id: '/_auth/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthProjectsIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/users/': {
      id: '/_auth/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthUsersIndexImport
      parentRoute: typeof AuthUsersImport
    }
    '/_auth/users/$userId/settings': {
      id: '/_auth/users/$userId/settings'
      path: '/$userId/settings'
      fullPath: '/users/$userId/settings'
      preLoaderRoute: typeof AuthUsersUserIdSettingsImport
      parentRoute: typeof AuthUsersImport
    }
    '/_auth/projects/$projectId/': {
      id: '/_auth/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthProjectsProjectIdIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/projects/$projectId/analyses/$analysisId/superuser': {
      id: '/_auth/projects/$projectId/analyses/$analysisId/superuser'
      path: '/projects/$projectId/analyses/$analysisId/superuser'
      fullPath: '/projects/$projectId/analyses/$analysisId/superuser'
      preLoaderRoute: typeof AuthProjectsProjectIdAnalysesAnalysisIdSuperuserImport
      parentRoute: typeof AuthImport
    }
    '/_auth/projects/$projectId/analyses/$analysisId/': {
      id: '/_auth/projects/$projectId/analyses/$analysisId/'
      path: '/projects/$projectId/analyses/$analysisId'
      fullPath: '/projects/$projectId/analyses/$analysisId'
      preLoaderRoute: typeof AuthProjectsProjectIdAnalysesAnalysisIdIndexImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthUsersRouteChildren {
  AuthUsersIndexRoute: typeof AuthUsersIndexRoute
  AuthUsersUserIdSettingsRoute: typeof AuthUsersUserIdSettingsRoute
}

const AuthUsersRouteChildren: AuthUsersRouteChildren = {
  AuthUsersIndexRoute: AuthUsersIndexRoute,
  AuthUsersUserIdSettingsRoute: AuthUsersUserIdSettingsRoute,
}

const AuthUsersRouteWithChildren = AuthUsersRoute._addFileChildren(
  AuthUsersRouteChildren,
)

interface AuthRouteChildren {
  AuthFunRoute: typeof AuthFunRoute
  AuthNoaccessRoute: typeof AuthNoaccessRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthUsersRoute: typeof AuthUsersRouteWithChildren
  AuthProjectsIndexRoute: typeof AuthProjectsIndexRoute
  AuthProjectsProjectIdIndexRoute: typeof AuthProjectsProjectIdIndexRoute
  AuthProjectsProjectIdAnalysesAnalysisIdSuperuserRoute: typeof AuthProjectsProjectIdAnalysesAnalysisIdSuperuserRoute
  AuthProjectsProjectIdAnalysesAnalysisIdIndexRoute: typeof AuthProjectsProjectIdAnalysesAnalysisIdIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthFunRoute: AuthFunRoute,
  AuthNoaccessRoute: AuthNoaccessRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthUsersRoute: AuthUsersRouteWithChildren,
  AuthProjectsIndexRoute: AuthProjectsIndexRoute,
  AuthProjectsProjectIdIndexRoute: AuthProjectsProjectIdIndexRoute,
  AuthProjectsProjectIdAnalysesAnalysisIdSuperuserRoute:
    AuthProjectsProjectIdAnalysesAnalysisIdSuperuserRoute,
  AuthProjectsProjectIdAnalysesAnalysisIdIndexRoute:
    AuthProjectsProjectIdAnalysesAnalysisIdIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service-unavailable': typeof ServiceUnavailableRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/fun': typeof AuthFunRoute
  '/noaccess': typeof AuthNoaccessRoute
  '/settings': typeof AuthSettingsRoute
  '/users': typeof AuthUsersRouteWithChildren
  '/projects': typeof AuthProjectsIndexRoute
  '/users/': typeof AuthUsersIndexRoute
  '/users/$userId/settings': typeof AuthUsersUserIdSettingsRoute
  '/projects/$projectId': typeof AuthProjectsProjectIdIndexRoute
  '/projects/$projectId/analyses/$analysisId/superuser': typeof AuthProjectsProjectIdAnalysesAnalysisIdSuperuserRoute
  '/projects/$projectId/analyses/$analysisId': typeof AuthProjectsProjectIdAnalysesAnalysisIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service-unavailable': typeof ServiceUnavailableRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/fun': typeof AuthFunRoute
  '/noaccess': typeof AuthNoaccessRoute
  '/settings': typeof AuthSettingsRoute
  '/projects': typeof AuthProjectsIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/users/$userId/settings': typeof AuthUsersUserIdSettingsRoute
  '/projects/$projectId': typeof AuthProjectsProjectIdIndexRoute
  '/projects/$projectId/analyses/$analysisId/superuser': typeof AuthProjectsProjectIdAnalysesAnalysisIdSuperuserRoute
  '/projects/$projectId/analyses/$analysisId': typeof AuthProjectsProjectIdAnalysesAnalysisIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service-unavailable': typeof ServiceUnavailableRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_auth/fun': typeof AuthFunRoute
  '/_auth/noaccess': typeof AuthNoaccessRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/users': typeof AuthUsersRouteWithChildren
  '/_auth/projects/': typeof AuthProjectsIndexRoute
  '/_auth/users/': typeof AuthUsersIndexRoute
  '/_auth/users/$userId/settings': typeof AuthUsersUserIdSettingsRoute
  '/_auth/projects/$projectId/': typeof AuthProjectsProjectIdIndexRoute
  '/_auth/projects/$projectId/analyses/$analysisId/superuser': typeof AuthProjectsProjectIdAnalysesAnalysisIdSuperuserRoute
  '/_auth/projects/$projectId/analyses/$analysisId/': typeof AuthProjectsProjectIdAnalysesAnalysisIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/forgot-password'
    | '/home'
    | '/reset-password'
    | '/service-unavailable'
    | '/signin'
    | '/signup'
    | '/verify-email'
    | '/fun'
    | '/noaccess'
    | '/settings'
    | '/users'
    | '/projects'
    | '/users/'
    | '/users/$userId/settings'
    | '/projects/$projectId'
    | '/projects/$projectId/analyses/$analysisId/superuser'
    | '/projects/$projectId/analyses/$analysisId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/forgot-password'
    | '/home'
    | '/reset-password'
    | '/service-unavailable'
    | '/signin'
    | '/signup'
    | '/verify-email'
    | '/fun'
    | '/noaccess'
    | '/settings'
    | '/projects'
    | '/users'
    | '/users/$userId/settings'
    | '/projects/$projectId'
    | '/projects/$projectId/analyses/$analysisId/superuser'
    | '/projects/$projectId/analyses/$analysisId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/forgot-password'
    | '/home'
    | '/reset-password'
    | '/service-unavailable'
    | '/signin'
    | '/signup'
    | '/verify-email'
    | '/_auth/fun'
    | '/_auth/noaccess'
    | '/_auth/settings'
    | '/_auth/users'
    | '/_auth/projects/'
    | '/_auth/users/'
    | '/_auth/users/$userId/settings'
    | '/_auth/projects/$projectId/'
    | '/_auth/projects/$projectId/analyses/$analysisId/superuser'
    | '/_auth/projects/$projectId/analyses/$analysisId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServiceUnavailableRoute: typeof ServiceUnavailableRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeRoute: HomeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServiceUnavailableRoute: ServiceUnavailableRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/forgot-password",
        "/home",
        "/reset-password",
        "/service-unavailable",
        "/signin",
        "/signup",
        "/verify-email"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/fun",
        "/_auth/noaccess",
        "/_auth/settings",
        "/_auth/users",
        "/_auth/projects/",
        "/_auth/projects/$projectId/",
        "/_auth/projects/$projectId/analyses/$analysisId/superuser",
        "/_auth/projects/$projectId/analyses/$analysisId/"
      ]
    },
    "/forgot-password": {
      "filePath": "forgot-password.tsx"
    },
    "/home": {
      "filePath": "home.tsx"
    },
    "/reset-password": {
      "filePath": "reset-password.tsx"
    },
    "/service-unavailable": {
      "filePath": "service-unavailable.tsx"
    },
    "/signin": {
      "filePath": "signin.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/verify-email": {
      "filePath": "verify-email.tsx"
    },
    "/_auth/fun": {
      "filePath": "_auth/fun.tsx",
      "parent": "/_auth"
    },
    "/_auth/noaccess": {
      "filePath": "_auth/noaccess.tsx",
      "parent": "/_auth"
    },
    "/_auth/settings": {
      "filePath": "_auth/settings.tsx",
      "parent": "/_auth"
    },
    "/_auth/users": {
      "filePath": "_auth/users.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/users/",
        "/_auth/users/$userId/settings"
      ]
    },
    "/_auth/projects/": {
      "filePath": "_auth/projects/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/users/": {
      "filePath": "_auth/users/index.tsx",
      "parent": "/_auth/users"
    },
    "/_auth/users/$userId/settings": {
      "filePath": "_auth/users/$userId/settings.tsx",
      "parent": "/_auth/users"
    },
    "/_auth/projects/$projectId/": {
      "filePath": "_auth/projects/$projectId/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/projects/$projectId/analyses/$analysisId/superuser": {
      "filePath": "_auth/projects/$projectId/analyses/$analysisId/superuser.tsx",
      "parent": "/_auth"
    },
    "/_auth/projects/$projectId/analyses/$analysisId/": {
      "filePath": "_auth/projects/$projectId/analyses/$analysisId/index.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
