// This file is auto-generated by @hey-api/openapi-ts

/**
 * Analysis
 */
export type Analysis = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Modified At
     */
    modified_at: string;
    /**
     * Content
     */
    content?: string | null;
    status?: AnalysisStatus;
    /**
     * Id
     */
    id: number;
    /**
     * Project Id
     */
    project_id: number;
};

/**
 * AnalysisStatus
 */
export type AnalysisStatus = 'pending' | 'in_progress' | 'completed' | 'failed';

/**
 * Body_login-login_access_token
 */
export type BodyLoginLoginAccessToken = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Body_projects-upload_file
 */
export type BodyProjectsUploadFile = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * EmailVerificationRequest
 * Request body for email verification.
 */
export type EmailVerificationRequest = {
    /**
     * Token
     */
    token: string;
};

/**
 * File
 * Schema for file data returned to clients (excludes stored_filename).
 */
export type File = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Modified At
     */
    modified_at: string;
    /**
     * Id
     */
    id: number;
    /**
     * Project Id
     */
    project_id: number;
    /**
     * Filename
     */
    filename: string;
    /**
     * Content Type
     */
    content_type?: string | null;
    /**
     * Size
     */
    size: number;
};

/**
 * FullAnalysis
 */
export type FullAnalysis = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Modified At
     */
    modified_at: string;
    /**
     * Content
     */
    content?: string | null;
    status?: AnalysisStatus;
    /**
     * Id
     */
    id: number;
    /**
     * Project Id
     */
    project_id: number;
    /**
     * Intermediate Results Content
     */
    intermediate_results_content?: string | null;
    /**
     * Intermediate Results
     */
    intermediate_results?: {
        [key: string]: string;
    } | null;
};

/**
 * HTTPError
 */
export type HttpError = {
    /**
     * Detail
     */
    detail: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 * Request body for password reset.
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PasswordRecoveryRequest
 * Request body for password recovery.
 */
export type PasswordRecoveryRequest = {
    /**
     * Email
     */
    email: string;
};

/**
 * Project
 */
export type Project = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Modified At
     */
    modified_at: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Owner Id
     */
    owner_id: number;
};

/**
 * ProjectCreate
 */
export type ProjectCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ProjectListItem
 * Project with inline statistics and owner info for list views.
 */
export type ProjectListItem = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Modified At
     */
    modified_at: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Owner Id
     */
    owner_id: number;
    /**
     * File Count
     * Number of files in the project
     */
    file_count?: number;
    /**
     * Analysis Count
     * Number of analyses in the project
     */
    analysis_count?: number;
    /**
     * Owner Email
     * Email of the project owner
     */
    owner_email: string;
};

/**
 * ProjectListResponse
 * Paginated list of projects.
 */
export type ProjectListResponse = {
    /**
     * Items
     * Projects in this page
     */
    items: Array<ProjectListItem>;
    /**
     * Total
     * Total number of projects matching the filter
     */
    total: number;
};

/**
 * ProjectUpdate
 */
export type ProjectUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ResendVerificationRequest
 * Request body for resending email verification.
 */
export type ResendVerificationRequest = {
    /**
     * Email
     */
    email: string;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * User
 */
export type User = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Modified At
     */
    modified_at: string;
    /**
     * Id
     */
    id: number;
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Is Email Verified
     */
    is_email_verified?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Has Llm Access
     */
    has_llm_access?: boolean;
    /**
     * Bonus Analyses
     */
    bonus_analyses?: number;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Has Llm Access
     */
    has_llm_access?: boolean;
};

/**
 * UserListResponse
 * Paginated list of users.
 */
export type UserListResponse = {
    /**
     * Items
     * Users in this page
     */
    items: Array<User>;
    /**
     * Total
     * Total number of users matching the filter
     */
    total: number;
};

/**
 * UserStats
 * Statistics for a user's projects and analyses.
 */
export type UserStats = {
    /**
     * User Id
     * ID of the user these statistics belong to
     */
    user_id: number;
    /**
     * Project Count
     * Number of projects owned by this user
     */
    project_count?: number;
    /**
     * Analysis Count
     * Number of analyses across all user's projects
     */
    analysis_count?: number;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Has Llm Access
     */
    has_llm_access?: boolean | null;
    /**
     * Bonus Analyses
     */
    bonus_analyses?: number | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type LoginLoginAccessTokenData = {
    body: BodyLoginLoginAccessToken;
    path?: never;
    query?: never;
    url: '/api/login/access-token';
};

export type LoginLoginAccessTokenErrors = {
    /**
     * Incorrect email or password
     */
    401: HttpError;
    /**
     * Email not verified
     */
    403: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type LoginLoginAccessTokenError = LoginLoginAccessTokenErrors[keyof LoginLoginAccessTokenErrors];

export type LoginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginLoginAccessTokenResponse = LoginLoginAccessTokenResponses[keyof LoginLoginAccessTokenResponses];

export type LoginRegisterData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/register';
};

export type LoginRegisterErrors = {
    /**
     * Email already registered
     */
    400: HttpError;
    /**
     * Registration is disabled
     */
    403: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type LoginRegisterError = LoginRegisterErrors[keyof LoginRegisterErrors];

export type LoginRegisterResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type LoginRegisterResponse = LoginRegisterResponses[keyof LoginRegisterResponses];

export type LoginVerifyEmailData = {
    body: EmailVerificationRequest;
    path?: never;
    query?: never;
    url: '/api/verify-email';
};

export type LoginVerifyEmailErrors = {
    /**
     * Invalid or expired token
     */
    400: HttpError;
    /**
     * User not found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginVerifyEmailError = LoginVerifyEmailErrors[keyof LoginVerifyEmailErrors];

export type LoginVerifyEmailResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginVerifyEmailResponse = LoginVerifyEmailResponses[keyof LoginVerifyEmailResponses];

export type LoginResendVerificationData = {
    body: ResendVerificationRequest;
    path?: never;
    query?: never;
    url: '/api/resend-verification';
};

export type LoginResendVerificationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginResendVerificationError = LoginResendVerificationErrors[keyof LoginResendVerificationErrors];

export type LoginResendVerificationResponses = {
    /**
     * Verification email sent (if user exists and not verified)
     */
    200: Message;
};

export type LoginResendVerificationResponse = LoginResendVerificationResponses[keyof LoginResendVerificationResponses];

export type LoginRecoverPasswordData = {
    body: PasswordRecoveryRequest;
    path?: never;
    query?: never;
    url: '/api/password-recovery';
};

export type LoginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordError = LoginRecoverPasswordErrors[keyof LoginRecoverPasswordErrors];

export type LoginRecoverPasswordResponses = {
    /**
     * Password recovery email sent (if user exists)
     */
    200: Message;
};

export type LoginRecoverPasswordResponse = LoginRecoverPasswordResponses[keyof LoginRecoverPasswordResponses];

export type LoginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/reset-password';
};

export type LoginResetPasswordErrors = {
    /**
     * Invalid or expired token
     */
    400: HttpError;
    /**
     * User not found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginResetPasswordError = LoginResetPasswordErrors[keyof LoginResetPasswordErrors];

export type LoginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginResetPasswordResponse = LoginResetPasswordResponses[keyof LoginResetPasswordResponses];

export type UsersGetUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * User Ids
         */
        user_ids?: string | null;
        /**
         * Emails
         */
        emails?: string | null;
        /**
         * Search
         */
        search?: string | null;
        /**
         * Limit
         */
        limit?: number | null;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/users';
};

export type UsersGetUsersErrors = {
    /**
     * Inactive user
     */
    400: HttpError;
    /**
     * Not authenticated
     */
    401: HttpError;
    /**
     * Could not validate credentials or user doesn't have enough privileges
     */
    403: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type UsersGetUsersError = UsersGetUsersErrors[keyof UsersGetUsersErrors];

export type UsersGetUsersResponses = {
    /**
     * Successful Response
     */
    200: UserListResponse;
};

export type UsersGetUsersResponse = UsersGetUsersResponses[keyof UsersGetUsersResponses];

export type UsersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type UsersCreateUserErrors = {
    /**
     * Inactive user
     */
    400: HttpError;
    /**
     * Not authenticated
     */
    401: HttpError;
    /**
     * Could not validate credentials or user doesn't have enough privileges
     */
    403: HttpError;
    /**
     * User with this email already exists
     */
    409: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type UsersCreateUserError = UsersCreateUserErrors[keyof UsersCreateUserErrors];

export type UsersCreateUserResponses = {
    /**
     * Successful Response
     */
    201: User;
};

export type UsersCreateUserResponse = UsersCreateUserResponses[keyof UsersCreateUserResponses];

export type UsersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type UsersDeleteUserErrors = {
    /**
     * Inactive user
     */
    400: HttpError;
    /**
     * Not authenticated
     */
    401: HttpError;
    /**
     * Could not validate credentials or user doesn't have enough privileges
     */
    403: HttpError;
    /**
     * User not found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersGetUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type UsersGetUserErrors = {
    /**
     * Inactive user
     */
    400: HttpError;
    /**
     * Not authenticated
     */
    401: HttpError;
    /**
     * Could not validate credentials or user doesn't have enough privileges
     */
    403: HttpError;
    /**
     * User not found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type UsersGetUserError = UsersGetUserErrors[keyof UsersGetUserErrors];

export type UsersGetUserResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type UsersGetUserResponse = UsersGetUserResponses[keyof UsersGetUserResponses];

export type UsersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type UsersUpdateUserErrors = {
    /**
     * Inactive user
     */
    400: HttpError;
    /**
     * Not authenticated
     */
    401: HttpError;
    /**
     * Could not validate credentials or user doesn't have enough privileges
     */
    403: HttpError;
    /**
     * User not found
     */
    404: HttpError;
    /**
     * User with this email already exists
     */
    409: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors];

export type UsersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses];

export type UsersGetUserStatisticsData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/users/{user_id}/statistics';
};

export type UsersGetUserStatisticsErrors = {
    /**
     * Inactive user
     */
    400: HttpError;
    /**
     * Not authenticated
     */
    401: HttpError;
    /**
     * Could not validate credentials or user doesn't have enough privileges
     */
    403: HttpError;
    /**
     * User not found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type UsersGetUserStatisticsError = UsersGetUserStatisticsErrors[keyof UsersGetUserStatisticsErrors];

export type UsersGetUserStatisticsResponses = {
    /**
     * Successful Response
     */
    200: UserStats;
};

export type UsersGetUserStatisticsResponse = UsersGetUserStatisticsResponses[keyof UsersGetUserStatisticsResponses];

export type MeDeleteMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type MeDeleteMeErrors = {
    /**
     * Inactive user
     */
    400: HttpError;
    /**
     * Not authenticated
     */
    401: HttpError;
    /**
     * Could not validate credentials or user doesn't have enough privileges
     */
    403: HttpError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type MeDeleteMeError = MeDeleteMeErrors[keyof MeDeleteMeErrors];

export type MeDeleteMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type MeDeleteMeResponse = MeDeleteMeResponses[keyof MeDeleteMeResponses];

export type MeReadMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type MeReadMeErrors = {
    /**
     * Inactive user
     */
    400: HttpError;
    /**
     * Not authenticated
     */
    401: HttpError;
    /**
     * Could not validate credentials or user doesn't have enough privileges
     */
    403: HttpError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type MeReadMeError = MeReadMeErrors[keyof MeReadMeErrors];

export type MeReadMeResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type MeReadMeResponse = MeReadMeResponses[keyof MeReadMeResponses];

export type MeUpdateMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type MeUpdateMeErrors = {
    /**
     * Inactive user
     */
    400: HttpError;
    /**
     * Not authenticated
     */
    401: HttpError;
    /**
     * Could not validate credentials or user doesn't have enough privileges
     */
    403: HttpError;
    /**
     * User not found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type MeUpdateMeError = MeUpdateMeErrors[keyof MeUpdateMeErrors];

export type MeUpdateMeResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type MeUpdateMeResponse = MeUpdateMeResponses[keyof MeUpdateMeResponses];

export type MeUpdateMePasswordData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/me/password';
};

export type MeUpdateMePasswordErrors = {
    /**
     * Incorrect password, new password is the same as current, or inactive user
     */
    400: HttpError;
    /**
     * Not authenticated
     */
    401: HttpError;
    /**
     * Could not validate credentials or user doesn't have enough privileges
     */
    403: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type MeUpdateMePasswordError = MeUpdateMePasswordErrors[keyof MeUpdateMePasswordErrors];

export type MeUpdateMePasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type MeUpdateMePasswordResponse = MeUpdateMePasswordResponses[keyof MeUpdateMePasswordResponses];

export type ProjectsListProjectsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number | null;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/projects';
};

export type ProjectsListProjectsErrors = {
    /**
     * Inactive user
     */
    400: HttpError;
    /**
     * Not authenticated
     */
    401: HttpError;
    /**
     * Could not validate credentials or user doesn't have enough privileges
     */
    403: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type ProjectsListProjectsError = ProjectsListProjectsErrors[keyof ProjectsListProjectsErrors];

export type ProjectsListProjectsResponses = {
    /**
     * Successful Response
     */
    200: ProjectListResponse;
};

export type ProjectsListProjectsResponse = ProjectsListProjectsResponses[keyof ProjectsListProjectsResponses];

export type ProjectsCreateProjectData = {
    body: ProjectCreate;
    path?: never;
    query?: never;
    url: '/api/projects';
};

export type ProjectsCreateProjectErrors = {
    /**
     * Inactive user
     */
    400: HttpError;
    /**
     * Not authenticated
     */
    401: HttpError;
    /**
     * Could not validate credentials or user doesn't have enough privileges
     */
    403: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type ProjectsCreateProjectError = ProjectsCreateProjectErrors[keyof ProjectsCreateProjectErrors];

export type ProjectsCreateProjectResponses = {
    /**
     * Successful Response
     */
    200: Project;
};

export type ProjectsCreateProjectResponse = ProjectsCreateProjectResponses[keyof ProjectsCreateProjectResponses];

export type ProjectsDeleteProjectData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/api/projects/{project_id}';
};

export type ProjectsDeleteProjectErrors = {
    /**
     * Inactive user
     */
    400: HttpError;
    /**
     * Not authenticated
     */
    401: HttpError;
    /**
     * Could not validate credentials or user doesn't have enough privileges
     */
    403: HttpError;
    /**
     * Project not found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type ProjectsDeleteProjectError = ProjectsDeleteProjectErrors[keyof ProjectsDeleteProjectErrors];

export type ProjectsDeleteProjectResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ProjectsDeleteProjectResponse = ProjectsDeleteProjectResponses[keyof ProjectsDeleteProjectResponses];

export type ProjectsGetProjectData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/api/projects/{project_id}';
};

export type ProjectsGetProjectErrors = {
    /**
     * Inactive user
     */
    400: HttpError;
    /**
     * Not authenticated
     */
    401: HttpError;
    /**
     * Could not validate credentials or user doesn't have enough privileges
     */
    403: HttpError;
    /**
     * Project not found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type ProjectsGetProjectError = ProjectsGetProjectErrors[keyof ProjectsGetProjectErrors];

export type ProjectsGetProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectListItem;
};

export type ProjectsGetProjectResponse = ProjectsGetProjectResponses[keyof ProjectsGetProjectResponses];

export type ProjectsUpdateProjectData = {
    body: ProjectUpdate;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/api/projects/{project_id}';
};

export type ProjectsUpdateProjectErrors = {
    /**
     * Inactive user
     */
    400: HttpError;
    /**
     * Not authenticated
     */
    401: HttpError;
    /**
     * Could not validate credentials or user doesn't have enough privileges
     */
    403: HttpError;
    /**
     * Project not found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type ProjectsUpdateProjectError = ProjectsUpdateProjectErrors[keyof ProjectsUpdateProjectErrors];

export type ProjectsUpdateProjectResponses = {
    /**
     * Successful Response
     */
    200: Project;
};

export type ProjectsUpdateProjectResponse = ProjectsUpdateProjectResponses[keyof ProjectsUpdateProjectResponses];

export type ProjectsGetProjectOwnerData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/api/projects/{project_id}/owner';
};

export type ProjectsGetProjectOwnerErrors = {
    /**
     * Inactive user
     */
    400: HttpError;
    /**
     * Not authenticated
     */
    401: HttpError;
    /**
     * Could not validate credentials or user doesn't have enough privileges
     */
    403: HttpError;
    /**
     * Project not found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type ProjectsGetProjectOwnerError = ProjectsGetProjectOwnerErrors[keyof ProjectsGetProjectOwnerErrors];

export type ProjectsGetProjectOwnerResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type ProjectsGetProjectOwnerResponse = ProjectsGetProjectOwnerResponses[keyof ProjectsGetProjectOwnerResponses];

export type ProjectsDeleteAllProjectFilesData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/api/projects/{project_id}/files';
};

export type ProjectsDeleteAllProjectFilesErrors = {
    /**
     * Inactive user
     */
    400: HttpError;
    /**
     * Not authenticated
     */
    401: HttpError;
    /**
     * Could not validate credentials or user doesn't have enough privileges
     */
    403: HttpError;
    /**
     * Project not found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type ProjectsDeleteAllProjectFilesError = ProjectsDeleteAllProjectFilesErrors[keyof ProjectsDeleteAllProjectFilesErrors];

export type ProjectsDeleteAllProjectFilesResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ProjectsDeleteAllProjectFilesResponse = ProjectsDeleteAllProjectFilesResponses[keyof ProjectsDeleteAllProjectFilesResponses];

export type ProjectsListProjectFilesData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/api/projects/{project_id}/files';
};

export type ProjectsListProjectFilesErrors = {
    /**
     * Inactive user
     */
    400: HttpError;
    /**
     * Not authenticated
     */
    401: HttpError;
    /**
     * Could not validate credentials or user doesn't have enough privileges
     */
    403: HttpError;
    /**
     * Project not found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type ProjectsListProjectFilesError = ProjectsListProjectFilesErrors[keyof ProjectsListProjectFilesErrors];

export type ProjectsListProjectFilesResponses = {
    /**
     * Response Projects-List Project Files
     * Successful Response
     */
    200: Array<File>;
};

export type ProjectsListProjectFilesResponse = ProjectsListProjectFilesResponses[keyof ProjectsListProjectFilesResponses];

export type ProjectsUploadFileData = {
    body: BodyProjectsUploadFile;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/api/projects/{project_id}/files';
};

export type ProjectsUploadFileErrors = {
    /**
     * Inactive user
     */
    400: HttpError;
    /**
     * Not authenticated
     */
    401: HttpError;
    /**
     * Could not validate credentials or user doesn't have enough privileges
     */
    403: HttpError;
    /**
     * File not found
     */
    404: HttpError;
    /**
     * File too large or project limits exceeded
     */
    413: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type ProjectsUploadFileError = ProjectsUploadFileErrors[keyof ProjectsUploadFileErrors];

export type ProjectsUploadFileResponses = {
    /**
     * Successful Response
     */
    200: File;
};

export type ProjectsUploadFileResponse = ProjectsUploadFileResponses[keyof ProjectsUploadFileResponses];

export type ProjectsDeleteFileData = {
    body?: never;
    path: {
        /**
         * File Id
         */
        file_id: number;
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/api/projects/{project_id}/files/{file_id}';
};

export type ProjectsDeleteFileErrors = {
    /**
     * Inactive user
     */
    400: HttpError;
    /**
     * Not authenticated
     */
    401: HttpError;
    /**
     * Could not validate credentials or user doesn't have enough privileges
     */
    403: HttpError;
    /**
     * File not found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type ProjectsDeleteFileError = ProjectsDeleteFileErrors[keyof ProjectsDeleteFileErrors];

export type ProjectsDeleteFileResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ProjectsDeleteFileResponse = ProjectsDeleteFileResponses[keyof ProjectsDeleteFileResponses];

export type ProjectsGetFileMetadataData = {
    body?: never;
    path: {
        /**
         * File Id
         */
        file_id: number;
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/api/projects/{project_id}/files/{file_id}';
};

export type ProjectsGetFileMetadataErrors = {
    /**
     * Inactive user
     */
    400: HttpError;
    /**
     * Not authenticated
     */
    401: HttpError;
    /**
     * Could not validate credentials or user doesn't have enough privileges
     */
    403: HttpError;
    /**
     * File not found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type ProjectsGetFileMetadataError = ProjectsGetFileMetadataErrors[keyof ProjectsGetFileMetadataErrors];

export type ProjectsGetFileMetadataResponses = {
    /**
     * Successful Response
     */
    200: File;
};

export type ProjectsGetFileMetadataResponse = ProjectsGetFileMetadataResponses[keyof ProjectsGetFileMetadataResponses];

export type ProjectsDownloadFileContentData = {
    body?: never;
    path: {
        /**
         * File Id
         */
        file_id: number;
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/api/projects/{project_id}/files/{file_id}/content';
};

export type ProjectsDownloadFileContentErrors = {
    /**
     * Inactive user
     */
    400: HttpError;
    /**
     * Not authenticated
     */
    401: HttpError;
    /**
     * Could not validate credentials or user doesn't have enough privileges
     */
    403: HttpError;
    /**
     * File not found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type ProjectsDownloadFileContentError = ProjectsDownloadFileContentErrors[keyof ProjectsDownloadFileContentErrors];

export type ProjectsDownloadFileContentResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ProjectsDownloadProjectArchiveData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/api/projects/{project_id}/archive';
};

export type ProjectsDownloadProjectArchiveErrors = {
    /**
     * Inactive user
     */
    400: HttpError;
    /**
     * Not authenticated
     */
    401: HttpError;
    /**
     * Could not validate credentials or user doesn't have enough privileges
     */
    403: HttpError;
    /**
     * Project not found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type ProjectsDownloadProjectArchiveError = ProjectsDownloadProjectArchiveErrors[keyof ProjectsDownloadProjectArchiveErrors];

export type ProjectsDownloadProjectArchiveResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AnalysesDeleteAllProjectAnalysesData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/api/projects/{project_id}/analyses';
};

export type AnalysesDeleteAllProjectAnalysesErrors = {
    /**
     * Inactive user
     */
    400: HttpError;
    /**
     * Not authenticated
     */
    401: HttpError;
    /**
     * Could not validate credentials or user doesn't have enough privileges
     */
    403: HttpError;
    /**
     * Project not found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type AnalysesDeleteAllProjectAnalysesError = AnalysesDeleteAllProjectAnalysesErrors[keyof AnalysesDeleteAllProjectAnalysesErrors];

export type AnalysesDeleteAllProjectAnalysesResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type AnalysesDeleteAllProjectAnalysesResponse = AnalysesDeleteAllProjectAnalysesResponses[keyof AnalysesDeleteAllProjectAnalysesResponses];

export type AnalysesListProjectAnalysesData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/api/projects/{project_id}/analyses';
};

export type AnalysesListProjectAnalysesErrors = {
    /**
     * Inactive user
     */
    400: HttpError;
    /**
     * Not authenticated
     */
    401: HttpError;
    /**
     * Could not validate credentials or user doesn't have enough privileges
     */
    403: HttpError;
    /**
     * Project not found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type AnalysesListProjectAnalysesError = AnalysesListProjectAnalysesErrors[keyof AnalysesListProjectAnalysesErrors];

export type AnalysesListProjectAnalysesResponses = {
    /**
     * Response Analyses-List Project Analyses
     * Successful Response
     */
    200: Array<Analysis>;
};

export type AnalysesListProjectAnalysesResponse = AnalysesListProjectAnalysesResponses[keyof AnalysesListProjectAnalysesResponses];

export type AnalysesCreateAnalysisData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/api/projects/{project_id}/analyses';
};

export type AnalysesCreateAnalysisErrors = {
    /**
     * Inactive user
     */
    400: HttpError;
    /**
     * Not authenticated
     */
    401: HttpError;
    /**
     * Could not validate credentials or user doesn't have enough privileges
     */
    403: HttpError;
    /**
     * Project not found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * No analyses remaining
     */
    429: HttpError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type AnalysesCreateAnalysisError = AnalysesCreateAnalysisErrors[keyof AnalysesCreateAnalysisErrors];

export type AnalysesCreateAnalysisResponses = {
    /**
     * Successful Response
     */
    200: Analysis;
};

export type AnalysesCreateAnalysisResponse = AnalysesCreateAnalysisResponses[keyof AnalysesCreateAnalysisResponses];

export type AnalysesDeleteAnalysisData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: number;
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/api/projects/{project_id}/analyses/{analysis_id}';
};

export type AnalysesDeleteAnalysisErrors = {
    /**
     * Inactive user
     */
    400: HttpError;
    /**
     * Not authenticated
     */
    401: HttpError;
    /**
     * Could not validate credentials or user doesn't have enough privileges
     */
    403: HttpError;
    /**
     * Analysis not found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type AnalysesDeleteAnalysisError = AnalysesDeleteAnalysisErrors[keyof AnalysesDeleteAnalysisErrors];

export type AnalysesDeleteAnalysisResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type AnalysesDeleteAnalysisResponse = AnalysesDeleteAnalysisResponses[keyof AnalysesDeleteAnalysisResponses];

export type AnalysesGetAnalysisData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: number;
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/api/projects/{project_id}/analyses/{analysis_id}';
};

export type AnalysesGetAnalysisErrors = {
    /**
     * Inactive user
     */
    400: HttpError;
    /**
     * Not authenticated
     */
    401: HttpError;
    /**
     * Could not validate credentials or user doesn't have enough privileges
     */
    403: HttpError;
    /**
     * Analysis not found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type AnalysesGetAnalysisError = AnalysesGetAnalysisErrors[keyof AnalysesGetAnalysisErrors];

export type AnalysesGetAnalysisResponses = {
    /**
     * Successful Response
     */
    200: Analysis;
};

export type AnalysesGetAnalysisResponse = AnalysesGetAnalysisResponses[keyof AnalysesGetAnalysisResponses];

export type AnalysesGetAnalysisPdfData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: number;
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/api/projects/{project_id}/analyses/{analysis_id}/pdf';
};

export type AnalysesGetAnalysisPdfErrors = {
    /**
     * Analysis is not completed or does not have content
     */
    400: HttpError;
    /**
     * Not authenticated
     */
    401: HttpError;
    /**
     * Could not validate credentials or user doesn't have enough privileges
     */
    403: HttpError;
    /**
     * Analysis not found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type AnalysesGetAnalysisPdfError = AnalysesGetAnalysisPdfErrors[keyof AnalysesGetAnalysisPdfErrors];

export type AnalysesGetAnalysisPdfResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AnalysesGetFullAnalysisData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: number;
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/api/projects/{project_id}/analyses/{analysis_id}/full';
};

export type AnalysesGetFullAnalysisErrors = {
    /**
     * Inactive user
     */
    400: HttpError;
    /**
     * Not authenticated
     */
    401: HttpError;
    /**
     * Could not validate credentials or user doesn't have enough privileges
     */
    403: HttpError;
    /**
     * Analysis not found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: HttpError;
};

export type AnalysesGetFullAnalysisError = AnalysesGetFullAnalysisErrors[keyof AnalysesGetFullAnalysisErrors];

export type AnalysesGetFullAnalysisResponses = {
    /**
     * Successful Response
     */
    200: FullAnalysis;
};

export type AnalysesGetFullAnalysisResponse = AnalysesGetFullAnalysisResponses[keyof AnalysesGetFullAnalysisResponses];

export type HealthHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthHealthResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};